name: Python DB Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Initialize Database
      run: |
        python WithDB/init_database.py

    - name: Print working directory
      run: pwd
    
    - name: List files in the expected database directory
      run: |
        cdWithDB
        ls

    - name: Run db_test.py
      run: |
        cd WithDB
        python -m unittest db_test
