name: Python DB Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # Use the version of Python you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Assuming you have a requirements.txt at the root

    - name: Change to root directory
      run: |
        cd WithDB

    - name: Run db_test.py
      run: |
        python -m unittest db_test.py
