name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      sqlite:
        image: nouchka/sqlite3
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # Use the version of Python you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sqlalchemy # Add all necessary dependencies for your tests
        # Add any other setup you need here

    - name: Run Tests
      run: |
        python -m unittest discover -s . -p '*_test.py' # This will discover and run all tests
